require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# source 'https://github.com/CocoaPods/Specs.git'

# target "DeployTarget" do
#     common_target
#     pod 'HySDKDeploy', '= 3.6.2'
#     pod 'react-native-im-easemob/Deploy', :path => '../node_modules/react-native-im-easemob'
# end

target 'OpenImSdkExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-open-im-sdk', :path => '../..'

  # post_install do |installer|
  #   installer.pods_project.build_configurations.each do |configuration|
  #     installer.pods_project.build_settings(configuration.name)['VALID_ARCHS'] = []
  #   end
  # end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.87.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
